name: GCP Python 3.6 & 3.8
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x', 'pypy3.6', 'pypy3.8' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
        - name: Install dependencies
          run: |
            make install
        - name: Lint
          run: |
            make lint
        - name: PEP8 Format
          run: |
            make format
        - name: Test
          run: |
            make test
